[General]
TcpServerPort=0
ReportStats=false
MavlinkDialect=common

[UartEndpoint FC]
Device=/dev/ttyACM0
Baud=115200

[UdpEndpoint ToWFB]
Mode=Normal
Address=127.0.0.1
Port=14561

[UdpEndpoint FromWFB]
Mode=Server
Address=0.0.0.0
Port=14560
